package de.tu_berlin.citlab.testsuite.helpers;


import backtype.storm.tuple.Fields;
import backtype.storm.tuple.Tuple;
import backtype.storm.tuple.Values;
import de.tu_berlin.citlab.testsuite.mocks.TupleMock;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;


/**
 * Created by Constantin on 1/22/14.
 */
public final class TupleMockFactory
{

    public static ArrayList<Tuple> generateTupleList_ByFields(Values[] values, Fields fields)
    {
        //A maximum of values.length tickTuples will also be added to the TupleList:
        int randTickTupleCount = (int) Math.round(Math.random() * values.length);

        //Initialize the Tuple-List:
        int tupleListSize = values.length + randTickTupleCount;
        ArrayList<Tuple> tupleList = new ArrayList<Tuple>(tupleListSize);

        //First add the Value-Tuples:
        for(int n = 0 ; n < values.length ; n++){
            Values actVals = values[n];
            tupleList.add(TupleMock.mockTupleByFields(actVals, fields));
        }
        return tupleList;
    }

    /**
     * Generates an {@link java.util.ArrayList} of Twitter-Tuples. Each Twitter-Tuple has the {@link backtype.storm.tuple.Fields} "user", "tweet_id", "tweet".
     * <p>
     *     The <b>Twitter Tuple Generation</b> is done as follows:
     *     From the String-Array "users", a random user (with a pre-generated id) is taken and afterwards a tweet is generated by random words out of the
     *     dictionary.
     * </p>
     * @param users The User names that are submitting tweets. Each user has it's unique ip over the test-run.
     * @param dictionary The word-array of all words that could be found in a randomly generated tweet.
     * @param wordsPerTweet The word-count per tweet.
     * @param tupleCount The number of tuples, that the {@link java.util.ArrayList} should hold.
     * @param tickTupleRatio The ratio, how many tickTuples are apppended to the output {@link java.util.ArrayList}.
     *                       The ratio states the number of tickTuples per tweet-Tuples. A ratio of 2 means, that one tickTuple follows on two tweet-Tuples.
     *                       If the tickTupleRatio is 0, no {@link de.tu_berlin.citlab.testsuite.mocks.TupleMock tickTuples} will be generated.
     * @return An {@link java.util.ArrayList} of {@link de.tu_berlin.citlab.testsuite.mocks.TupleMock Tweet- & TickTuples (if tickTupleRatio > 0)}
     */
	public static ArrayList<Tuple> generateTwitterTuples(String[] users, String[] dictionary, int wordsPerTweet, int tupleCount, int tickTupleRatio)
	{
		Fields inputFields = new Fields("user", "tweet_id", "tweet");
		Map<String, Integer> userIDs = new HashMap<String, Integer>(users.length);
		initUserIDs(userIDs, users);
        int tickTupleCount = (tickTupleRatio == 0) ? 0 : tupleCount/tickTupleRatio;
		ArrayList<Tuple> tupleOutput = new ArrayList<Tuple>(tupleCount + tickTupleCount);

		for (int i = 0; i < tupleCount; i++) {

			Values actTupleVals = generateTweet(userIDs, users, dictionary, wordsPerTweet);
			Tuple actTuple = TupleMock.mockTupleByFields(actTupleVals, inputFields);
			tupleOutput.add(actTuple);


            if(tickTupleRatio > 0) {
                if ((i % tickTupleRatio) == 0) {
                    Tuple tickTuple = TupleMock.mockTickTuple();
                    tupleOutput.add(tickTuple);
                }
            }
		}

		return tupleOutput;
	}


	private static void initUserIDs(Map<String, Integer> userIDs, String[] users) {
		for (String actUser : users) {
			int randID = (int) Math.round(Math.random() * 10000);
			userIDs.put(actUser, randID);
		}
	}

	private static Values generateTweet(Map<String,Integer> userIDs, String[] users, String[] dictionary, int wordsPerTweet)
	{
		int randUserIndex = (int) Math.round(Math.random() * (users.length -1));
		String randUser = users[randUserIndex];

		int randUserID = userIDs.get(randUser);

		String tweet = "";
		for (int n = 0; n < wordsPerTweet; n++) {
			int randWordIndex = (int) Math.round(Math.random() * (dictionary.length -1));
			String randWord = dictionary[randWordIndex];
			if(n > 0){
				tweet += " ";
			}
			tweet += randWord;
		}

		return new Values(randUser, randUserID, tweet);
	}
}
